version: '3.8'
services:
    backend:
        build:
            context: .
            dockerfile: Dockerfile.backend
        ports:
            - "8080:8080"
        environment:
            - SPRING_PROFILES_ACTIVE=prod
        depends_on:
            - mongodb
    frontend:
        build:
            context: .
            dockerfile: Dockerfile.frontend
        ports:
            - "3000:3000"
        depends_on:
            - backend
    mongodb:
        image: mongo:latest
        ports:
            - "27017:27017"
        volumes:
            - mongo-data:/data/db

volumes:
    mongo-data:
