spring.application.name=vod_backend

spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

# MongoDB
spring.data.mongodb.uri=mongodb://localhost:27017/vods
spring.data.mongodb.database=vod-platform

# RabbitMQ
spring.rabbitmq.host=rabbitmq
spring.rabbitmq.port=5672
spring.rabbitmq.username=admin
spring.rabbitmq.password=admin
spring.rabbitmq.virtual-host=/

spring.data.mongodb.auto-index-creation=true

logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG

# Change this to a random value 256 bytes long
jwt.secret=YXNkZmFzZGZhcioasd7SDsadsad89a8asdkvHHHHsdaas56a982RmYXNkZmFzZGZhc2RmYXNkZg==

# If you use a different ports for different origins, change it here (default is 3000). Separate multiple origins with a comma.
# localhost:3000 if not in docker container, otherwise streamify_frontend:3000
cors.allowed.origins=http://localhost:3000

# If you use multiple harddrives for storing videos, add them here. Separate multiple locations with a comma.
# Example (LINUX):      /mnt/driveA/videos/,/mnt/driveB/videos/
# Example (WINDOWS):    C:/videos/,D:/videos/
video.storage.locations=D:/backup/TestVideoFolder/
web.stream.resource.locations=D:/backup/TestVideoFolder/
