spring.application.name=vod_backend

# application.properties
spring.servlet.multipart.max-file-size=2GB
spring.servlet.multipart.max-request-size=2GB
spring.http.multipart.enabled=true
spring.web.servlet.multipart.max-file-size=2GB
spring.web.servlet.multipart.max-request-size=2GB

server.tomcat.max-swallow-size=-1
server.tomcat.connection-timeout=60000



# MongoDB
spring.data.mongodb.uri=mongodb://localhost:27017/vods
spring.data.mongodb.database=vod-platform

spring.web.resources.add-mappings=true
spring.web.resources.chain.strategy.content.enabled=true
spring.web.resources.chain.strategy.content.paths=/**
spring.web.resources.chain.strategy.fixed.enabled=false

# RabbitMQ
spring.rabbitmq.host=rabbitmq
spring.rabbitmq.port=5672
spring.rabbitmq.username=admin
spring.rabbitmq.password=admin
spring.rabbitmq.virtual-host=/

spring.data.mongodb.auto-index-creation=true

logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG

# Change this to a random value 256 bytes long
jwt.secret=YXNkZmFzZGZhcioasd7SDsadsad89a8asdkvHHHHsdaas56a982RmYXNkZmFzZGZhc2RmYXNkZg==

# If you use a different ports for different origins, change it here (default is 3000). Separate multiple origins with a comma.
# localhost:3000 if not in docker container, otherwise streamify_frontend:3000
cors.allowed.origins=http://localhost:3000

# If you use a different harddrive for storing videos, add them here. Only one location is required.
# Example (LINUX):      /mnt/driveA/videos/
# Example (WINDOWS):    C:/videos/,D:/videos/
video.storage.locations=D:/backup/TestVideoFolder/

# If you use a different harddrive for storing streams, add them here. Multiple locations are allowed.
# Example (LINUX):      /mnt/driveA/videos/,/mnt/driveB/videos/
# Example (WINDOWS):    C:/videos/,D:/videos/
web.stream.resource.locations=D:/backup/TestVideoFolder/
